"""remove_respondent_personal_data

Revision ID: 0b772bfe0146
Revises: 3bca61d15f99
Create Date: 2025-08-28 23:21:48.231279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b772bfe0146'
down_revision: Union[str, None] = '3bca61d15f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_submissions', 'respondent_name')
    op.drop_column('questionnaire_submissions', 'respondent_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_submissions', sa.Column('respondent_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questionnaire_submissions', sa.Column('respondent_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
