"""add criador_id to questionnaires

Revision ID: 3bca61d15f99
Revises: f99ef9af4889
Create Date: 2025-08-15 18:49:45.422345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bca61d15f99'
down_revision: Union[str, None] = 'f99ef9af4889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('criador_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questionnaires', 'users', ['criador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaires', type_='foreignkey')
    op.drop_column('questionnaires', 'criador_id')
    # ### end Alembic commands ###
