"""add nascimento to users

Revision ID: 3e7568103153
Revises: f63800b574cd
Create Date: 2025-08-29 02:27:34.828819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7568103153'
down_revision: Union[str, None] = 'f63800b574cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nascimento', sa.Date(), nullable=False))
    op.drop_column('users', 'idade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'nascimento')
    # ### end Alembic commands ###
