"""adicionar campo caption nas perguntas

Revision ID: 967df56bd26a
Revises: 3e7568103153
Create Date: 2025-08-29 21:57:02.880594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967df56bd26a'
down_revision: Union[str, None] = '3e7568103153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('caption', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_questions_caption'), 'questions', ['caption'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_caption'), table_name='questions')
    op.drop_column('questions', 'caption')
    # ### end Alembic commands ###
